name: Docker CI

on:
  push:
    branches: [ "master" ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REPOSITORY: isanjay112 # name of Docker Hub ID
      IMAGE_NAME: plutus-mvc
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build
        run: |
          docker build . -f Plutus.Mvc/Dockerfile -t $DOCKER_REPOSITORY/$IMAGE_NAME:0.0.$GITHUB_RUN_NUMBER -t $DOCKER_REPOSITORY/$IMAGE_NAME:latest
          
      - name: Push
        run: |
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:0.0.$GITHUB_RUN_NUMBER
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:latest
